// Static zodiac metadata — fixed astrological attributes, never changes.
// Daily/weekly/monthly/yearly READING content lives in horoscopes.json (regenerated by cron).

export type Element = 'Fire' | 'Earth' | 'Air' | 'Water';
export type Modality = 'Cardinal' | 'Fixed' | 'Mutable';

export interface Sign {
  slug: string;
  name: string;
  glyph: string;
  dates: string;          // human-readable date range
  element: Element;
  modality: Modality;
  ruler: string;          // ruling planet
  house: string;          // signature house (literary anchor)
  pairs: string[];        // slugs that pair well (compatibility)
  tarot: { name: string; slug: string }; // associated Major Arcana
}

export const SIGNS: Sign[] = [
  { slug: 'aries',       name: 'Aries',       glyph: '♈', dates: 'March 21 – April 19',     element: 'Fire',  modality: 'Cardinal', ruler: 'Mars',    house: 'first house',      pairs: ['leo', 'sagittarius'],   tarot: { name: 'The Emperor',  slug: 'the-emperor' } },
  { slug: 'taurus',      name: 'Taurus',      glyph: '♉', dates: 'April 20 – May 20',       element: 'Earth', modality: 'Fixed',    ruler: 'Venus',   house: 'second house',     pairs: ['virgo', 'capricorn'],   tarot: { name: 'The Hierophant', slug: 'the-hierophant' } },
  { slug: 'gemini',      name: 'Gemini',      glyph: '♊', dates: 'May 21 – June 20',        element: 'Air',   modality: 'Mutable',  ruler: 'Mercury', house: 'third house',      pairs: ['libra', 'aquarius'],    tarot: { name: 'The Lovers',   slug: 'the-lovers' } },
  { slug: 'cancer',      name: 'Cancer',      glyph: '♋', dates: 'June 21 – July 22',       element: 'Water', modality: 'Cardinal', ruler: 'the Moon', house: 'fourth house',    pairs: ['scorpio', 'pisces'],    tarot: { name: 'The Chariot',  slug: 'the-chariot' } },
  { slug: 'leo',         name: 'Leo',         glyph: '♌', dates: 'July 23 – August 22',     element: 'Fire',  modality: 'Fixed',    ruler: 'the Sun',  house: 'fifth house',     pairs: ['aries', 'sagittarius'], tarot: { name: 'Strength',     slug: 'strength' } },
  { slug: 'virgo',       name: 'Virgo',       glyph: '♍', dates: 'August 23 – September 22', element: 'Earth', modality: 'Mutable',  ruler: 'Mercury', house: 'sixth house',      pairs: ['taurus', 'capricorn'],  tarot: { name: 'The Hermit',   slug: 'the-hermit' } },
  { slug: 'libra',       name: 'Libra',       glyph: '♎', dates: 'September 23 – October 22', element: 'Air',  modality: 'Cardinal', ruler: 'Venus',   house: 'seventh house',    pairs: ['gemini', 'aquarius'],   tarot: { name: 'Justice',      slug: 'justice' } },
  { slug: 'scorpio',     name: 'Scorpio',     glyph: '♏', dates: 'October 23 – November 21', element: 'Water', modality: 'Fixed',    ruler: 'Pluto',   house: 'eighth house',     pairs: ['cancer', 'pisces'],     tarot: { name: 'Death',        slug: 'death' } },
  { slug: 'sagittarius', name: 'Sagittarius', glyph: '♐', dates: 'November 22 – December 21', element: 'Fire', modality: 'Mutable',  ruler: 'Jupiter', house: 'ninth house',      pairs: ['aries', 'leo'],         tarot: { name: 'Temperance',   slug: 'temperance' } },
  { slug: 'capricorn',   name: 'Capricorn',   glyph: '♑', dates: 'December 22 – January 19', element: 'Earth', modality: 'Cardinal', ruler: 'Saturn',  house: 'tenth house',      pairs: ['taurus', 'virgo'],      tarot: { name: 'The Devil',    slug: 'the-devil' } },
  { slug: 'aquarius',    name: 'Aquarius',    glyph: '♒', dates: 'January 20 – February 18', element: 'Air',   modality: 'Fixed',    ruler: 'Uranus',  house: 'eleventh house',   pairs: ['gemini', 'libra'],      tarot: { name: 'The Star',     slug: 'the-star' } },
  { slug: 'pisces',      name: 'Pisces',      glyph: '♓', dates: 'February 19 – March 20',   element: 'Water', modality: 'Mutable',  ruler: 'Neptune', house: 'twelfth house',    pairs: ['cancer', 'scorpio'],    tarot: { name: 'The Moon',     slug: 'the-moon' } },
];

export const SIGN_BY_SLUG: Record<string, Sign> = Object.fromEntries(SIGNS.map((s) => [s.slug, s]));

export const PERIODS = ['weekly', 'monthly', 'yearly'] as const;
export type Period = (typeof PERIODS)[number];

export const PERIOD_LABEL: Record<Period, string> = {
  weekly: 'This Week',
  monthly: 'This Month',
  yearly: '2026 Yearly',
};
